/** Community Wayfinding: booking procedures must attach the authenticated account and must not accept a patient id from the client. */
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "../_core/context";
const db = vi.hoisted(() => ({ createAppointment: vi.fn(), listOwnAppointments: vi.fn(), listProviderAppointments: vi.fn() }));
vi.mock("../appointmentDb", () => db);
import { appRouter } from "../routers";
const user = { id: 91, openId: "booking-user", name: "Test", email: "test@example.com", loginMethod: "test", role: "user" as const, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() };
const ctx = { user, req: { protocol: "https", headers: {} }, res: { clearCookie: vi.fn() } } as unknown as TrpcContext;
beforeEach(() => { vi.clearAllMocks(); db.createAppointment.mockResolvedValue({ appointmentRef: "PXK-TEST" }); db.listOwnAppointments.mockResolvedValue([]); });
describe("PxK appointment booking", () => { it("uses the authenticated user and requires consent to book", async () => { const caller = appRouter.createCaller(ctx); await caller.appointments.book({ doctorId: "ananya-rao", scheduledAt: "2026-08-30T10:00:00.000Z", complaintLedger: [{ question: "Main concern", answer: "Cough" }], consentAcknowledged: true, profile: { displayName: "Asha", ageYears: 28, gender: "woman" } }); expect(db.createAppointment).toHaveBeenCalledWith(expect.objectContaining({ userId: 91, doctorId: "ananya-rao", complaintLedgerJson: JSON.stringify([{ question: "Main concern", answer: "Cough" }]), consentVersion: "appointment-consent-v1", profile: { displayName: "Asha", ageYears: 28, gender: "woman" } })); }); it("accepts a complete screening ledger and transparent factor trace", async () => { const caller = appRouter.createCaller(ctx); const ledger = Array.from({ length: 25 }, (_, index) => ({ question: `Question ${index + 1}`, answer: "Patient-reported answer" })); await caller.appointments.book({ doctorId: "ananya-rao", scheduledAt: "2026-08-30T10:00:00.000Z", complaintLedger: ledger, consentAcknowledged: true, profile: { displayName: "Asha", ageYears: 28, gender: "woman" } }); expect(db.createAppointment).toHaveBeenCalledWith(expect.objectContaining({ complaintLedgerJson: JSON.stringify(ledger) })); }); it("lists appointments only under the signed-in account", async () => { const caller = appRouter.createCaller(ctx); await caller.appointments.listMine(); expect(db.listOwnAppointments).toHaveBeenCalledWith(91); }); it("rejects provider appointment review for a non-admin account", async () => { const caller = appRouter.createCaller(ctx); await expect(caller.appointments.listForProvider()).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(db.listProviderAppointments).not.toHaveBeenCalled(); }); });
