/** Community Wayfinding: voice transcription requires consent and passes only an authenticated user’s requested audio to the service. */
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "../_core/context";
const storage = vi.hoisted(() => ({ storagePut: vi.fn(), storageGetSignedUrl: vi.fn() })); const speech = vi.hoisted(() => ({ transcribeAudio: vi.fn() }));
vi.mock("../storage", () => storage); vi.mock("../_core/voiceTranscription", () => speech);
import { appRouter } from "../routers";
const user = { id: 12, openId: "voice-user", name: "Voice", email: "voice@example.com", loginMethod: "test", role: "user" as const, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }; const ctx = { user, req: { protocol: "https", headers: {} }, res: { clearCookie: vi.fn() } } as unknown as TrpcContext;
beforeEach(() => { vi.clearAllMocks(); storage.storagePut.mockResolvedValue({ key: "pxk-voice/12/input.webm", url: "/manus-storage/pxk-voice/12/input.webm" }); storage.storageGetSignedUrl.mockResolvedValue("https://signed.example/voice.webm"); speech.transcribeAudio.mockResolvedValue({ task: "transcribe", language: "en", duration: 1, text: "I have a cough", segments: [] }); });
describe("PxK voice transcription", () => { it("stores and transcribes a consented audio clip under the authenticated user path", async () => { const caller = appRouter.createCaller(ctx); const result = await caller.voice.transcribe({ audioBase64: Buffer.from("test audio clip for pxk").toString("base64"), mimeType: "audio/webm", language: "en", consentAcknowledged: true }); expect(result.text).toBe("I have a cough"); expect(storage.storagePut).toHaveBeenCalledWith(expect.stringContaining("pxk-voice/12/"), expect.any(Buffer), "audio/webm"); expect(storage.storageGetSignedUrl).toHaveBeenCalledWith("pxk-voice/12/input.webm"); expect(speech.transcribeAudio).toHaveBeenCalledWith(expect.objectContaining({ audioUrl: "https://signed.example/voice.webm" })); }); });
