/** Community Wayfinding: the about route grounds PxK in a real problem context without inventing evidence or identities. */
import { PathwayRail } from "@/components/PathwayRail";
import { CtaSection, SectionHeading, StatCard } from "@/components/UiPrimitives";
import { ASSETS } from "@/data/mockData";
import { Accessibility, Activity, Languages, Route } from "lucide-react";

export default function About() {
  return <main>
    <section className="inner-hero"><div className="container grid items-end gap-10 lg:grid-cols-[1.05fr_0.95fr]"><div><p className="eyebrow">About PxK · SIH 2026</p><h1 className="display-title mt-4 text-5xl sm:text-6xl">Built for the gap between a health concern and the right care.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--muted-ink)]">PxK is a frontend prototype that explores patient-first screening, specialist navigation, and longitudinal monitoring for rural and semi-urban Karnataka.</p><p className="about-route-caption">Route annotation · designed for multilingual, mobile-first care navigation</p></div><div className="about-mark"><img src={ASSETS.logo} alt="PxK route mark" /><p>Right patient.<br />Right doctor.<br /><strong>Right time.</strong></p></div></div><div className="container mt-12"><PathwayRail active={1} compact /></div></section>
    <section className="section-space bg-[var(--paper)]"><div className="container grid gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><SectionHeading eyebrow="The problem space" title="Care pathways can be hard to find." copy="Rural and semi-urban patients may face uncertainty about which kind of medical professional to approach, while healthcare facilities work with limited resources." /></div><div className="about-problem"><article><Route /><h2>Make the route clearer</h2><p>Structure a concern before a patient arrives at the next point of care.</p></article><article><Languages /><h2>Make access feel local</h2><p>Prioritise understandable language and low-friction interactions.</p></article><article><Activity /><h2>Make follow-up visible</h2><p>Keep a simple timeline of reported symptoms and screening events.</p></article><article><Accessibility /><h2>Make interface choices practical</h2><p>Design for mobile use, legibility, and a future offline-first concept.</p></article></div></div></section>
    <section className="section-space"><div className="container"><SectionHeading eyebrow="Project context" title="PxK · prepared by Team Errorists for SIH 2026." /><div className="mt-10 grid gap-4 md:grid-cols-3"><StatCard label="Theme" value="04" copy="MEDTECH / BIOTECH / HEALTHTECH" /><StatCard label="Problem statement" value="SIH007" copy="Prototype framing supplied by Team Errorists." /><StatCard label="Product focus" value="PxK" copy="Patient navigation and screening decision support." /></div></div></section>
    <section className="team-section"><div className="container"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><SectionHeading eyebrow="Prototype makers" title="Prepared by Team Errorists." copy="Team-member identities have intentionally not been fabricated for this prototype." /><p className="max-w-xs font-mono text-[0.62rem] uppercase leading-5 tracking-[0.13em] text-[var(--muted-ink)]">Member details can be added when confirmed.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1, 2, 3, 4].map((member) => <article className="team-card" key={member}><div className="team-avatar">{String(member).padStart(2, "0")}</div><p className="mt-6 text-lg font-bold tracking-[-0.035em] text-[var(--ink)]">Team Member</p><p className="mt-1 text-sm text-[var(--muted-ink)]">PxK prototype · SIH 2026</p></article>)}</div></div></section>
    <section className="container py-10"><CtaSection /></section>
  </main>;
}
