/** Community Wayfinding: the provider view distils patient-reported summaries to protect time for clinical conversation. */
import { PathwayRail } from "@/components/PathwayRail";
import { PatientCard, SpecialtyBadge, StatCard } from "@/components/UiPrimitives";
import { DOCTOR_PATIENTS } from "@/data/mockData";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ClipboardList, Clock3, Languages, UserRoundCheck } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

export default function DoctorDashboard() {
  const [selected, setSelected] = useState<(typeof DOCTOR_PATIENTS)[number] | null>(null);
  return <main className="dashboard-page provider-page">
    <div className="container py-8 lg:py-12">
      <div className="dashboard-topline"><p className="eyebrow">Provider view · demo mode</p><Link className="text-button" href="/">Return home</Link></div>
      <div className="mt-5 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="display-title text-5xl">Doctor dashboard.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-[var(--muted-ink)]">Structured patient-reported screening summaries, prepared to support a focused clinical conversation.</p></div><div className="provider-badge"><UserRoundCheck className="h-5 w-5" /><span>Fictional clinical workspace</span></div></div>
      <div className="provider-route-anchor"><div><p className="eyebrow">PxK route / care handoff</p><p className="mt-2 text-sm font-bold text-[var(--ink)]">Patient intake moves into a concise review sheet.</p></div><p className="provider-language-note"><Languages className="h-4 w-4" />English · ಕನ್ನಡ · Tulu-ready</p></div>
      <div className="mt-7"><PathwayRail active={2} compact /></div>
      <div className="mt-10 grid gap-4 sm:grid-cols-3"><StatCard label="New summaries" value="04" copy="Patient-reported check-ins awaiting review." /><StatCard label="Follow-ups" value="02" copy="Screenings with a next clinical step recorded." /><StatCard label="Attention" value="01" copy="A reported change to review in conversation." /></div>
      <section className="mt-10 grid gap-6 xl:grid-cols-[1.16fr_0.84fr]"><div className="provider-list"><div className="flex items-end justify-between gap-3"><div><p className="eyebrow">Today’s overview</p><h2 className="mt-2 text-3xl font-bold tracking-[-0.05em] text-[var(--ink)]">Patient screening summaries</h2></div><span className="font-mono text-[0.62rem] uppercase tracking-[0.14em] text-[var(--muted-ink)]">4 items</span></div><div className="mt-6 divide-y divide-[var(--line)]">{DOCTOR_PATIENTS.map((patient) => <PatientCard key={patient.id} patient={patient} onClick={() => setSelected(patient)} />)}</div></div><aside className="provider-aside"><p className="eyebrow">The PxK benefit</p><h2 className="mt-3 text-3xl font-bold tracking-[-0.05em] text-[var(--ink)]">Less time gathering basic information.</h2><p className="mt-5 text-base leading-7 text-[var(--muted-ink)]">More time focused on the clinical consultation. PxK carries a patient’s reported concern, time frame, and preliminary route into a compact summary.</p><div className="provider-flow"><span><ClipboardList /></span><i /><span><Clock3 /></span><i /><span><UserRoundCheck /></span></div><p className="mt-5 font-mono text-[0.62rem] uppercase leading-5 tracking-[0.14em] text-[var(--muted-ink)]">Intake → summary → consultation</p></aside></section>
    </div>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-w-2xl border-[var(--line)] bg-[var(--paper)] p-0 sm:rounded-[1.35rem]"><div className="p-7 sm:p-9">{selected && <><DialogHeader><p className="eyebrow">Patient screening summary · Prototype data</p><DialogTitle className="mt-2 text-3xl font-bold tracking-[-0.055em] text-[var(--ink)]">{selected.id}</DialogTitle><DialogDescription className="mt-2 text-base leading-7 text-[var(--muted-ink)]">This fictional summary demonstrates structured patient-reported information before a consultation.</DialogDescription></DialogHeader><div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="detail-cell"><span>Chief complaint</span><strong>{selected.complaint}</strong></div><div className="detail-cell"><span>Screening date</span><strong>{selected.date}</strong></div><div className="detail-cell sm:col-span-2"><span>Preliminary profile</span><strong>{selected.profile}</strong></div></div><div className="result-route mt-6"><p className="eyebrow">Follow-up status</p><p className="mt-3 text-base font-bold text-[var(--ink)]">{selected.status}</p><div className="mt-4"><SpecialtyBadge specialty="Clinical review remains essential" /></div></div></>}</div></DialogContent></Dialog>
  </main>;
}
