/** Community Wayfinding: the home route tells the entire PxK journey with product interfaces, not marketing decoration. */
import { DoctorMatching } from "@/components/DoctorMatching";
import { PathwayRail } from "@/components/PathwayRail";
import { ScreeningDemo } from "@/components/ScreeningDemo";
import { CtaSection, DemoModePill, HealthProfileCard, MonitoringTimeline, SectionHeading, SpecialtyBadge, StatCard } from "@/components/UiPrimitives";
import { ASSETS, DEFAULT_SESSION, LANGUAGE_COPY, type Language } from "@/data/mockData";
import { ArrowDownRight, ArrowRight, ChartNoAxesCombined, ChevronRight, ClipboardList, HeartPulse, Languages, MapPin, ShieldCheck, Stethoscope } from "lucide-react";
import { Link } from "wouter";

export default function Home({ language }: { language: Language }) {
  const copy = LANGUAGE_COPY[language];
  const scrollToDemo = () => document.getElementById("demo")?.scrollIntoView({ behavior: "smooth", block: "start" });
  return <main>
    <section className="hero-section"><div className="hero-orbit hero-orbit--one" /><div className="hero-orbit hero-orbit--two" /><div className="container relative z-10 grid items-center gap-12 py-14 lg:grid-cols-[1.02fr_0.98fr] lg:py-20 xl:py-24"><div className="max-w-2xl"><div className="flex flex-wrap items-center gap-3"><DemoModePill /><span className="hero-kicker">Multilingual health navigation · Karnataka</span></div><h1 className={`hero-title mt-7 ${language === "kn" ? "font-kannada" : ""}`}>{copy.hero}</h1><p className={`mt-7 max-w-xl text-lg leading-8 text-[var(--muted-ink)] ${language === "kn" ? "font-kannada" : ""}`}>{copy.support}</p>{language === "tulu" && <p className="mt-4 text-xs leading-5 text-[var(--muted-ink)]">Tulu labels will be introduced after verified linguistic review; this demonstration intentionally avoids invented translations.</p>}<div className="mt-9 flex flex-wrap gap-3"><button className="btn btn-primary" onClick={scrollToDemo}>{copy.start}<ArrowRight className="h-4 w-4" /></button><Link className="btn btn-outline" href="/how-it-works">See how it works <ArrowDownRight className="h-4 w-4" /></Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-[var(--muted-ink)]"><span className="inline-flex items-center gap-2"><Languages className="h-4 w-4 text-[var(--teal)]" />English · ಕನ್ನಡ · Tulu</span><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[var(--teal)]" />Decision support, not diagnosis</span></div></div><div className="hero-visual"><div className="hero-sheet hero-sheet--back" /><div className="hero-mini-card"><p className="route-label">Screening</p><p className="mt-1 text-sm font-bold text-[var(--ink)]">Question 2 of 3</p><span className="mt-3 block h-1.5 w-28 rounded-full bg-[var(--line)]"><span className="block h-full w-2/3 rounded-full bg-[var(--turmeric)]" /></span></div><img src={ASSETS.heroPhone} alt="PxK patient screening interface on a smartphone" className="hero-phone" /><div className="hero-path-label"><span>01</span><p>Patient-led intake<br /><strong>in their language</strong></p></div></div></div></section>
    <section className="pathway-band"><div className="container"><PathwayRail active={1} /></div></section>
    <section className="section-space bg-[var(--paper)]"><div className="container grid items-center gap-12 lg:grid-cols-[0.94fr_1.06fr]"><div><SectionHeading eyebrow="Patient-first care navigation" title="Healthcare navigation should start with the patient." copy="Patients should not have to guess which doctor to visit. PxK turns their concerns into a structured preliminary health profile and helps route them toward the appropriate specialist." /><Link className="text-button mt-8" href="/how-it-works">Follow the PxK pathway <ChevronRight className="h-4 w-4" /></Link></div><div className="value-visual"><div className="value-route-label"><span>02</span><p>Structured before<br />the consultation</p></div><HealthProfileCard session={DEFAULT_SESSION} /></div></div></section>
    <section className="feature-collection section-space"><div className="container"><SectionHeading eyebrow="Three connected capabilities" title="A clearer route, built around the patient." copy="Each stage carries forward the information that matters, avoiding repeated storytelling while keeping the patient’s next step in view." /><div className="mt-14 space-y-5"><article className="feature-row"><div className="feature-index"><span>01</span><ClipboardList className="h-5 w-5" /></div><div className="feature-copy"><p className="eyebrow">Intelligent screening</p><h3>Start with the patient’s words.</h3><p>Symptoms, medical history, lifestyle factors, and existing conditions become a Chief Complaint and Preliminary Health Profile — not a medical diagnosis.</p><div className="mt-5 flex flex-wrap gap-2"><span className="micro-tag">Symptoms</span><span className="micro-tag">History</span><span className="micro-tag">Lifestyle</span></div></div><div className="feature-asset"><img src={ASSETS.profileSheet} alt="Structured PxK preliminary health profile visual" /></div></article><article className="feature-row feature-row--reverse"><div className="feature-index"><span>02</span><Stethoscope className="h-5 w-5" /></div><div className="feature-copy"><p className="eyebrow">Specialty-first matching</p><h3>Stop guessing which doctor to visit.</h3><p>PxK surfaces fictional prototype choices using specialty, experience, fee, distance, and availability, so patients can prepare for the right kind of clinical conversation.</p><div className="mt-5"><SpecialtyBadge specialty="Potential specialty route" /></div></div><div className="feature-asset"><img src={ASSETS.doctorMatch} alt="PxK specialist matching interface visual" /></div></article><article className="feature-row"><div className="feature-index"><span>03</span><ChartNoAxesCombined className="h-5 w-5" /></div><div className="feature-copy"><p className="eyebrow">Longitudinal monitoring</p><h3>Care doesn’t end after one screening.</h3><p>Repeated patient-reported check-ins create a readable record of reported changes and follow-up activity over time.</p><div className="mt-5"><span className="micro-tag">Patient-reported trend</span></div></div><div className="feature-asset"><img src={ASSETS.monitoring} alt="PxK monitoring route timeline visual" /></div></article></div></div></section>
    <section className="language-section section-space"><div className="container grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><SectionHeading eyebrow="Multilingual access" title="Healthcare should speak your language." copy="The screening interaction is designed to make language a core product feature, not an afterthought." /><p className="mt-7 text-sm leading-6 text-[var(--muted-ink)]"><strong className="text-[var(--ink)]">English · ಕನ್ನಡ · Tulu</strong><br />Tulu is represented only after language verification; the prototype keeps unverified wording clearly labelled.</p></div><div className="language-cards"><article className="language-card"><p className="route-label">English</p><p className="mt-5 text-2xl font-bold leading-tight tracking-[-0.04em]">Where are you experiencing discomfort?</p><span className="language-route">01</span></article><article className="language-card language-card--kannada"><p className="route-label">ಕನ್ನಡ</p><p className="font-kannada mt-5 text-2xl font-bold leading-tight">ನಿಮಗೆ ಎಲ್ಲಿ ತೊಂದರೆ ಅನುಭವವಾಗುತ್ತಿದೆ?</p><span className="language-route">02</span></article><article className="language-card language-card--tulu"><p className="route-label">Tulu</p><p className="mt-5 text-lg font-bold leading-7 tracking-[-0.025em]">Verified local-language copy appears here after linguistic review.</p><span className="language-route">03</span></article></div></div></section>
    <section className="section-space bg-[var(--paper)]"><div className="container"><ScreeningDemo language={language} /></div></section>
    <section className="section-space"><div className="container"><div><SectionHeading eyebrow="Specialty-first routing" title="Practical choices, made comparable." copy="Compare a broader set of fictional clinician profiles by specialty, experience, fee, distance, availability, and the appointment slot that suits the patient." /><div className="route-callout mt-8"><MapPin className="h-5 w-5" /><p>All doctor information below is <strong>fictional prototype data</strong>, used only to demonstrate patient choice, appointment booking, and decision factors.</p></div></div><div className="mt-10"><DoctorMatching limit={6} title="Choose a clinician and book a review" /></div></div></section>
    <section className="monitoring-section section-space"><div className="container grid items-center gap-12 lg:grid-cols-[1fr_1fr]"><div className="monitoring-art"><img src={ASSETS.monitoring} alt="Illustrative PxK patient monitoring timeline" /><div className="monitoring-floating"><p className="route-label">Patient-reported trend</p><svg viewBox="0 0 260 78" role="img" aria-label="Illustrative symptom trend showing a change over several check-ins" className="mt-3 w-full"><path d="M4 61 C34 53, 45 45, 72 49 S115 38, 139 42 S179 16, 206 25 S235 18, 256 8" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" /><circle cx="72" cy="49" r="4" fill="#D99B14" /><circle cx="206" cy="25" r="4" fill="#B35B52" /></svg><div className="mt-3 flex justify-between font-mono text-[0.56rem] uppercase tracking-[0.12em] text-[var(--muted-ink)]"><span>Jun</span><span>Jul</span><span>Aug</span></div></div></div><div><SectionHeading eyebrow="Longitudinal record" title="Notice changes. Prepare follow-up." copy="A simple screening history can give patients and clinicians a clearer view of patient-reported changes, without replacing clinical judgement." /><MonitoringTimeline /><Link className="text-button mt-9" href="/patient">Explore patient monitoring <ChevronRight className="h-4 w-4" /></Link></div></div></section>
    <section className="trust-section bg-[#083E3D]"><div className="container"><div className="trust-inner"><div><p className="eyebrow text-[var(--turmeric-soft)]">A trust boundary</p><h2 className="display-title mt-4 text-4xl !text-white sm:text-5xl">PxK helps decide where to go next. It does not decide what you have.</h2></div><div className="trust-copy"><HeartPulse className="h-6 w-6 text-[var(--turmeric)]" /><p>PxK is designed as a screening and decision-support platform. Clinical diagnosis and treatment remain the responsibility of qualified healthcare professionals.</p></div></div></div></section>
    <section className="section-space bg-[var(--paper)]"><div className="container"><SectionHeading eyebrow="Designed for underserved communities" title="A system built to travel further." copy="PxK is designed to scale across rural and semi-urban communities in Karnataka through language access, lightweight interfaces, structured information, and a future-ready offline-first capture concept." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Language access" value="03" copy="English, Kannada, and Tulu-ready pathways." /><StatCard label="Care route" value="04" copy="Concern through continued monitoring." /><StatCard label="Interface" value="Lite" copy="Designed around clear, low-friction screens." /><StatCard label="Data" value="Local" copy="Prototype interactions stay in the browser session." /></div></div></section>
    <section className="container py-8 sm:py-12"><CtaSection /></section>
  </main>;
}
