/** Community Wayfinding: the explanatory route is editorial and stage-led, with no decorative process diagrams. */
import { PathwayRail } from "@/components/PathwayRail";
import { CtaSection, SectionHeading } from "@/components/UiPrimitives";
import { ASSETS } from "@/data/mockData";
import { Check, ClipboardList, HeartPulse, MapPin, Sparkles } from "lucide-react";

const stages = [
  { no: "01", title: "Patient intake", copy: "A multilingual structured questionnaire lets people describe a concern in language that feels familiar.", details: ["Symptoms and time frame", "Existing conditions", "Patient-reported context"], icon: ClipboardList, asset: ASSETS.heroPhone },
  { no: "02", title: "Chief Complaint & Preliminary Health Profile", copy: "Responses are translated into a concise summary that can be carried forward into the next stage.", details: ["Chief Complaint", "Relevant History", "Screening-oriented language"], icon: Sparkles, asset: ASSETS.profileSheet },
  { no: "03", title: "AI-assisted specialist routing", copy: "The prototype shows how matching can consider specialty, experience, fee, distance, and availability — without claiming a diagnosis.", details: ["Specialty context", "Comparable local factors", "Fictional prototype cards"], icon: MapPin, asset: ASSETS.doctorMatch },
  { no: "04", title: "Longitudinal monitoring", copy: "Repeated screenings form a readable timeline of reported symptoms and planned follow-up activity.", details: ["Screening history", "Reported symptom changes", "Clinical follow-up prompts"], icon: HeartPulse, asset: ASSETS.monitoring },
];

export default function HowItWorks() { return <main><section className="inner-hero"><div className="container"><p className="eyebrow">The PxK route</p><h1 className="display-title mt-4 max-w-4xl text-5xl sm:text-6xl">From a concern to a clearer clinical next step.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--muted-ink)]">A practical pathway designed to structure patient-reported information, guide specialist discovery, and maintain a lightweight record of reported follow-up.</p><div className="mt-12"><PathwayRail active={3} /></div></div></section><section className="section-space bg-[var(--paper)]"><div className="container"><SectionHeading eyebrow="Four stages" title="A route that carries context forward." /><div className="mt-12 space-y-8">{stages.map((stage, index) => { const Icon = stage.icon; return <article className={`stage-editorial ${index % 2 === 1 ? "stage-editorial--reverse" : ""}`} key={stage.no}><div className="stage-number"><span>{stage.no}</span><Icon className="h-5 w-5" /></div><div className="stage-content"><p className="eyebrow">Stage {stage.no}</p><h2>{stage.title}</h2><p>{stage.copy}</p><ul>{stage.details.map((detail) => <li key={detail}><Check className="h-4 w-4" />{detail}</li>)}</ul></div><div className="stage-image"><img src={stage.asset} alt={`Illustrative PxK product view for ${stage.title}`} /></div></article>; })}</div></div></section><section className="trust-section"><div className="container"><div className="trust-inner"><div><p className="eyebrow text-[var(--turmeric-soft)]">Decision support / not diagnosis</p><h2 className="display-title mt-4 text-4xl text-white">Good routing supports better conversations. It does not replace them.</h2></div><p className="trust-copy">PxK’s role is to organise information and make an appropriate next clinical conversation easier to identify. Diagnosis and treatment remain with qualified healthcare professionals.</p></div></div></section><section className="container py-10"><CtaSection /></section></main>; }
