/** Community Wayfinding: this model card describes the real NLP intake and deterministic route layers without overstating medical capability. */
import { PathwayRail } from "@/components/PathwayRail";
import { BrainCircuit, CheckCheck, CircleX, Database, LockKeyhole, ShieldCheck, Waypoints } from "lucide-react";
import { Link } from "wouter";

const capabilities = ["Classifies patient-written concerns into a respiratory, digestive, dental, or manual-route screening path.", "Shows a short summary and matched patient-reported terms before the questionnaire begins.", "Uses a deterministic rule layer to retain a visible rationale within the completed screening record.", "Keeps consented drafts scoped to the signed-in user so they can be resumed or discarded."];
const boundaries = ["It does not identify, confirm, or diagnose a disease or condition.", "It does not provide treatment, medication, dosage, or emergency assessment.", "It does not guarantee that a route is clinically appropriate for every person.", "It does not replace a qualified healthcare professional or local emergency service."];

export default function ModelCard() { return <main className="model-page"><div className="container py-8 lg:py-12"><div className="dashboard-topline"><p className="eyebrow">Model card · PxK Intake & Route System v0.2</p><Link className="text-button" href="/analytics">Return to analytics</Link></div><div className="mt-7 grid gap-10 lg:grid-cols-[1fr_.7fr]"><div><h1 className="display-title text-5xl">An NLP-assisted intake and route system, not a diagnosis model.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--muted-ink)]">PxK takes a consented free-text concern, selects a focused questionnaire, and records the patient-reported factors that shaped the next-step route. The language model is server-side; the visible screening-route logic remains auditable in the user’s record.</p></div><div className="model-identity"><BrainCircuit /><p className="eyebrow">System identity</p><h2>PxK Intake &<br />Route System v0.2</h2><span>Server-side NLP · authenticated drafts · decision support only</span></div></div><div className="mt-12"><PathwayRail active={2} compact /></div><section className="model-facts"><article><BrainCircuit /><p className="eyebrow">Layer 01</p><h2>Language intake</h2><p>A structured server-side classification selects an appropriate screening route from patient-written text. If unavailable, a bounded keyword fallback keeps the prototype functional.</p></article><article><Waypoints /><p className="eyebrow">Layer 02</p><h2>Route trace</h2><p>The screening record carries the selected responses and the route factors forward in a clinician-readable structure.</p></article><article><Database /><p className="eyebrow">Layer 03</p><h2>Saved progress</h2><p>Consented drafts are scoped to the signed-in account, allowing a patient to pause, resume, or discard an unfinished check-in.</p></article></section><section className="model-boundaries"><div><p className="eyebrow">Designed boundaries</p><h2>What the system can and cannot do.</h2></div><div className="boundary-columns"><article><CheckCheck /><h3>It can</h3><ul>{capabilities.map((item) => <li key={item}>{item}</li>)}</ul></article><article><CircleX /><h3>It cannot</h3><ul>{boundaries.map((item) => <li key={item}>{item}</li>)}</ul></article></div></section><section className="model-governance"><ShieldCheck /><div><p className="eyebrow">Privacy and governance</p><h2>Consent, minimisation, and clinical review remain essential.</h2><p>Before free-text intake is processed, PxK requests explicit demo consent. A real-world deployment would also need clinically curated evaluation data, specialist review of route criteria, a security assessment, retention limits, regional privacy controls, and a formal escalation policy.</p></div><LockKeyhole className="model-lock" /></section></div></main>; }
