/** Community Wayfinding: appointment coordination stores only the patient profile, selected clinician, slot, and consented route reference required by this prototype. */
import { and, desc, eq } from "drizzle-orm";
import { appointments, patientProfiles, screeningRecords } from "../drizzle/schema";
import { getDb } from "./db";

export type PatientProfileInput = { displayName: string; ageYears: number; gender: string };
export type AppointmentInput = { userId: number; appointmentRef: string; doctorId: string; scheduledAt: Date; screeningRecordId?: string; patientNote?: string; complaintLedgerJson: string; consentVersion: string; profile: PatientProfileInput };
export async function createAppointment(input: AppointmentInput) { const db = await getDb(); if (!db) throw new Error("Database is unavailable"); await db.insert(patientProfiles).values({ userId: input.userId, ...input.profile }).onDuplicateKeyUpdate({ set: { ...input.profile, updatedAt: new Date() } }); await db.insert(appointments).values({ appointmentRef: input.appointmentRef, userId: input.userId, doctorId: input.doctorId, scheduledAt: input.scheduledAt, screeningRecordId: input.screeningRecordId || null, patientNote: input.patientNote || null, complaintLedgerJson: input.complaintLedgerJson, consentVersion: input.consentVersion }); const [record] = await db.select().from(appointments).where(and(eq(appointments.userId, input.userId), eq(appointments.appointmentRef, input.appointmentRef))).limit(1); return record; }
export async function listOwnAppointments(userId: number) { const db = await getDb(); if (!db) throw new Error("Database is unavailable"); return db.select().from(appointments).where(eq(appointments.userId, userId)).orderBy(desc(appointments.scheduledAt)); }
export async function listProviderAppointments() { const db = await getDb(); if (!db) throw new Error("Database is unavailable"); return db.select({ appointment: appointments, profile: patientProfiles, screening: screeningRecords }).from(appointments).innerJoin(patientProfiles, eq(patientProfiles.userId, appointments.userId)).leftJoin(screeningRecords, and(eq(screeningRecords.userId, appointments.userId), eq(screeningRecords.publicId, appointments.screeningRecordId))).orderBy(desc(appointments.createdAt)); }
