/** Community Wayfinding: server-side NLP only maps a patient’s own words to a screening route; it never diagnoses, triages, or recommends treatment. */
import { invokeLLM, listLLMModels } from "./_core/llm";

export type IntakeRoute = "respiratory" | "digestive" | "dental" | "general";
export type IntakeLanguage = "en" | "kn" | "tulu" | "kok";
export type IntakeClassification = { route: IntakeRoute; confidence: "low" | "medium" | "high"; matchedTerms: string[]; summary: string; nextStep: string; safetyNotice: string };

const schema = { type: "json_schema" as const, json_schema: { name: "pxk_intake_route", strict: true, schema: { type: "object", properties: { route: { type: "string", enum: ["respiratory", "digestive", "dental", "general"] }, confidence: { type: "string", enum: ["low", "medium", "high"] }, matchedTerms: { type: "array", items: { type: "string" }, maxItems: 5 }, summary: { type: "string", maxLength: 220 }, nextStep: { type: "string", maxLength: 180 }, safetyNotice: { type: "string", maxLength: 220 } }, required: ["route", "confidence", "matchedTerms", "summary", "nextStep", "safetyNotice"], additionalProperties: false } } };
const genericSafety = "This tool does not diagnose or determine urgency. If you believe you need immediate help, contact local emergency services or a qualified healthcare professional.";
const terms: Record<Exclude<IntakeRoute, "general">, string[]> = { respiratory: ["cough", "breath", "breathing", "wheeze", "chest", "asthma", "lung", "smoke", "fever", "cold"], digestive: ["stomach", "abdomen", "abdominal", "acidity", "heartburn", "vomit", "nausea", "bowel", "stool", "diarrhea", "constipation", "digestion"], dental: ["tooth", "teeth", "gum", "jaw", "dental", "mouth", "ulcer", "cavity", "root canal", "sensitivity"] };

export function classifyByKeywords(text: string): IntakeClassification { const value = text.toLowerCase(); const scores = Object.fromEntries(Object.entries(terms).map(([route, routeTerms]) => [route, routeTerms.filter((term) => value.includes(term)).length])) as Record<Exclude<IntakeRoute, "general">, number>; const best = (Object.entries(scores).sort((a, b) => b[1] - a[1])[0] || ["general", 0]) as [IntakeRoute, number]; const matched = best[0] === "general" ? [] : terms[best[0] as Exclude<IntakeRoute, "general">].filter((term) => value.includes(term)).slice(0, 5); const route = best[1] ? best[0] : "general"; const confidence = best[1] >= 3 ? "high" : best[1] >= 1 ? "medium" : "low"; const label = route === "respiratory" ? "respiratory" : route === "digestive" ? "digestive" : route === "dental" ? "dental" : "general health"; return { route, confidence, matchedTerms: matched, summary: route === "general" ? "The description did not clearly match one of the focused screening routes in this prototype." : `The description includes terms that align with PxK’s ${label} screening route.`, nextStep: route === "general" ? "Choose a focused route manually so that the questions match your concern." : `Continue to the ${label} questionnaire to structure the concern for a clinical conversation.`, safetyNotice: genericSafety }; }

export async function classifyConcern(text: string, language: IntakeLanguage): Promise<IntakeClassification> { const fallback = classifyByKeywords(text); try { const { data } = await listLLMModels(); const model = data.find((item) => item.id === "gpt-5-mini")?.id || data.find((item) => item.id.startsWith("gpt-5"))?.id; const response = await invokeLLM({ model, messages: [{ role: "system", content: "You are PxK Intake Router. Classify a patient-written concern into respiratory, digestive, dental, or general so the app can select a questionnaire. Never diagnose diseases, predict outcomes, recommend medication/treatment, or state urgency. Use patient-reported language. If the concern could be serious, state only that the tool cannot determine urgency and advise professional help if the user believes immediate help is needed. Output only the requested JSON." }, { role: "user", content: `Display language: ${language}. Patient concern: ${text.slice(0, 1200)}` }], response_format: schema, maxTokens: 500 }); const content = response.choices[0]?.message?.content; if (!content || typeof content !== "string") return fallback; const parsed = JSON.parse(content) as IntakeClassification; if (!["respiratory", "digestive", "dental", "general"].includes(parsed.route)) return fallback; return { ...parsed, matchedTerms: parsed.matchedTerms.slice(0, 5), safetyNotice: genericSafety }; } catch (error) { console.warn("[PxK intake] LLM routing unavailable; using local keyword fallback", error); return fallback; } }
