/** Community Wayfinding: matching controls show realistic local choices without simulating a live medical service. */
import { DoctorCard, SpecialtyBadge } from "@/components/UiPrimitives";
import { DOCTORS, type Doctor } from "@/data/mockData";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ArrowDownUp, CalendarDays, MapPin, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
type SortKey = "match" | "distance" | "fee" | "availability" | "experience";
const SORT_LABELS: Record<SortKey, string> = { match: "Best match", distance: "Distance", fee: "Consultation fee", availability: "Availability", experience: "Experience" };

export function DoctorMatching({ limit, title = "Recommended specialists" }: { limit?: number; title?: string }) {
  const [sort, setSort] = useState<SortKey>("match"); const [selected, setSelected] = useState<Doctor | null>(null);
  const doctors = useMemo(() => [...DOCTORS].sort((a, b) => { if (sort === "distance") return a.distance - b.distance; if (sort === "fee") return a.fee - b.fee; if (sort === "experience") return b.experience - a.experience; if (sort === "availability") return a.availability.localeCompare(b.availability); return a.specialty === "Pulmonologist" ? -1 : b.specialty === "Pulmonologist" ? 1 : 0; }), [sort]); const visible = limit ? doctors.slice(0, limit) : doctors;
  return <section id="matching" className="scroll-mt-28" aria-labelledby="matching-title"><div className="flex flex-col gap-5 border-b border-[var(--line)] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Prototype data · Local interaction</p><h3 id="matching-title" className="mt-2 text-3xl font-bold tracking-[-0.05em] text-[var(--ink)]">{title}</h3></div><label className="sort-select"><ArrowDownUp className="h-4 w-4" aria-hidden="true" /><span className="sr-only">Sort doctors by</span><select value={sort} onChange={(event) => setSort(event.target.value as SortKey)}>{(Object.keys(SORT_LABELS) as SortKey[]).map((key) => <option value={key} key={key}>{SORT_LABELS[key]}</option>)}</select></label></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((doctor, index) => <DoctorCard key={doctor.id} doctor={doctor} rank={index + 1} onView={setSelected} />)}</div><Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-w-xl border-[var(--line)] bg-[var(--paper)] p-0 sm:rounded-[1.35rem]"><div className="p-7 sm:p-8">{selected && <><DialogHeader><p className="eyebrow">Prototype doctor profile</p><DialogTitle className="mt-2 text-3xl font-bold tracking-[-0.055em] text-[var(--ink)]">{selected.name}</DialogTitle><DialogDescription className="mt-3 text-base leading-7 text-[var(--muted-ink)]">Fictional profile used to demonstrate PxK’s local matching interface.</DialogDescription></DialogHeader><div className="mt-6"><SpecialtyBadge specialty={selected.specialty} /></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="detail-cell"><span>Practice</span><strong>{selected.experience} years</strong></div><div className="detail-cell"><span>Consultation</span><strong>₹{selected.fee}</strong></div><div className="detail-cell"><span>Distance</span><strong>{selected.distance} km</strong></div><div className="detail-cell"><span>Available</span><strong>{selected.availability}</strong></div></div><div className="result-route mt-6"><p className="eyebrow">Why this appears</p><p className="mt-3 text-sm leading-6 text-[var(--ink)]">{selected.match}</p></div></>}</div></DialogContent></Dialog></section>;
}
