/** Community Wayfinding: the screening interaction moves one clear, non-diagnostic step at a time. */
import { HealthProfileCard, ProgressIndicator, ScreeningQuestion, SpecialtyBadge } from "@/components/UiPrimitives";
import { makeSession, SCREENING_QUESTIONS, storeSession, type Language, type ScreeningSession } from "@/data/mockData";
import { ArrowLeft, ArrowRight, RotateCcw, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

export function ScreeningDemo({ language }: { language: Language }) {
  const [started, setStarted] = useState(false); const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>(["", "", ""]); const [result, setResult] = useState<ScreeningSession | null>(null); const question = SCREENING_QUESTIONS[step]; const hasAnswer = Boolean(answers[step]); const label = language === "kn" ? question.kannada : language === "tulu" ? `${question.question} (Tulu copy under review)` : question.question;
  const choose = (answer: string) => setAnswers((previous) => previous.map((value, index) => index === step ? answer : value)); const next = () => { if (!hasAnswer) return; if (step < SCREENING_QUESTIONS.length - 1) setStep((current) => current + 1); else { const session = makeSession(answers[0], answers[1], answers[2]); storeSession(session); setResult(session); } }; const reset = () => { setStarted(false); setStep(0); setAnswers(["", "", ""]); setResult(null); };
  return <section id="demo" className="screening-shell scroll-mt-28" aria-labelledby="screening-demo-title"><div className="screening-aside"><p className="eyebrow text-[var(--turmeric-soft)]">Interactive demonstration</p><h2 id="screening-demo-title" className="display-title mt-4 text-4xl text-white lg:text-5xl">From concern to a clearer next step.</h2><p className="mt-5 max-w-md text-base leading-7 text-white/70">A small, local-only demonstration of how patient-reported information can be structured before a clinical conversation.</p><div className="screening-note"><ShieldCheck className="h-5 w-5" /><p>PxK suggests a potential next point of consultation. It does not diagnose a condition.</p></div></div><div className="screening-panel">{!started ? <div className="flex min-h-[410px] flex-col justify-between"><div><p className="eyebrow">Patient route · 03 minutes</p><h3 className="mt-4 text-3xl font-bold tracking-[-0.055em] text-[var(--ink)]">Begin with what changed.</h3><p className="mt-4 max-w-md text-base leading-7 text-[var(--muted-ink)]">Answer three simple questions. This prototype uses no real medical data and stores your selections only in this browser session.</p></div><button className="btn btn-primary w-fit" onClick={() => setStarted(true)}>Start demo <ArrowRight className="h-4 w-4" /></button></div> : result ? <div className="animate-settle"><div className="flex flex-wrap items-center justify-between gap-3"><p className="eyebrow">Screening complete</p><button className="text-button" onClick={reset}><RotateCcw className="h-4 w-4" />Try again</button></div><HealthProfileCard session={result} /><div className="result-route"><p className="eyebrow">Why this recommendation?</p><p className="mt-3 text-base leading-7 text-[var(--ink)]">{result.nextStep}</p><div className="mt-5"><SpecialtyBadge specialty={result.potentialSpecialty} /></div></div><div className="mt-6 flex flex-wrap gap-3"><Link className="btn btn-primary" href="/patient">Open patient view <ArrowRight className="h-4 w-4" /></Link><a className="btn btn-outline" href="#matching">See recommended specialists</a></div></div> : <div className="animate-settle"><ProgressIndicator current={step + 1} total={SCREENING_QUESTIONS.length} /><div className="mt-9"><p className="route-label">Question {String(step + 1).padStart(2, "0")}</p><div className="mt-3"><ScreeningQuestion question={label} options={question.options} selected={answers[step]} onSelect={choose} /></div></div><div className="mt-10 flex items-center justify-between gap-3"><button className="btn btn-text" onClick={() => setStep((current) => Math.max(0, current - 1))} disabled={step === 0}><ArrowLeft className="h-4 w-4" />Back</button><button className="btn btn-primary" disabled={!hasAnswer} onClick={next}>{step === SCREENING_QUESTIONS.length - 1 ? "View profile" : "Continue"}<ArrowRight className="h-4 w-4" /></button></div></div>}</div></section>;
}
