/** Community Wayfinding: shared product components use field-sheet panels, route markers, and accessible controls. */
import type { Doctor, ScreeningSession } from "@/data/mockData";
import { CalendarDays, Check, ChartNoAxesCombined, ChevronRight, Clock3, MapPin, Stethoscope } from "lucide-react";
import { Link } from "wouter";

export function DemoModePill() { return <span className="demo-pill"><span aria-hidden="true" /> Demo mode</span>; }
export function SectionHeading({ eyebrow, title, copy, align = "left" }: { eyebrow: string; title: string; copy?: string; align?: "left" | "center" }) { return <div className={align === "center" ? "mx-auto max-w-3xl text-center" : "max-w-3xl"}><p className="eyebrow">{eyebrow}</p><h2 className="display-title mt-3 text-[clamp(2rem,4.2vw,4rem)]">{title}</h2>{copy && <p className="mt-5 max-w-2xl text-base leading-7 text-[var(--muted-ink)] md:text-lg">{copy}</p>}</div>; }
export function SpecialtyBadge({ specialty }: { specialty: string }) { return <span className="specialty-badge"><Stethoscope className="h-3.5 w-3.5" aria-hidden="true" />{specialty}</span>; }
export function ProgressIndicator({ current, total }: { current: number; total: number }) { const percent = Math.max(0, Math.min(100, Math.round((current / total) * 100))); return <div aria-label={`Question ${current} of ${total}`}><div className="flex items-center justify-between font-mono text-[0.62rem] uppercase tracking-[0.14em] text-[var(--muted-ink)]"><span>Screening progress</span><span>{percent}%</span></div><div className="progress-track mt-2"><span style={{ width: `${percent}%` }} /></div></div>; }
export function ScreeningQuestion({ question, options, selected, onSelect }: { question: string; options: Array<string | { value: string; label: string }>; selected?: string; onSelect: (option: string) => void }) { return <fieldset className="border-0 p-0"><legend className="text-xl font-bold tracking-[-0.035em] text-[var(--ink)]">{question}</legend><div className="mt-5 grid gap-2.5 sm:grid-cols-2">{options.map((item) => { const option = typeof item === "string" ? { value: item, label: item } : item; return <button type="button" key={option.value} className={`option-card ${selected === option.value ? "option-card--selected" : ""}`} onClick={() => onSelect(option.value)} aria-pressed={selected === option.value}><span>{option.label}</span>{selected === option.value && <Check className="h-4 w-4" />}</button>; })}</div></fieldset>; }
export function HealthProfileCard({ session, condensed = false }: { session: ScreeningSession; condensed?: boolean }) { return <section id="health-profile" className={`health-profile ${condensed ? "health-profile--condensed" : ""}`} aria-label="Preliminary Health Profile"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">Preliminary health profile</p><h3 className="mt-2 text-xl font-bold tracking-[-0.04em] text-[var(--ink)]">A structured next step</h3></div><span className="route-number">02</span></div><dl className="mt-6 grid gap-5 sm:grid-cols-2"><div><dt>Chief complaint</dt><dd>{session.chiefComplaint}</dd></div><div><dt>Relevant history</dt><dd>{session.relevantHistory}</dd></div><div className="sm:col-span-2"><dt>Potential specialty</dt><dd><SpecialtyBadge specialty={session.potentialSpecialty} /></dd></div></dl>{!condensed && <div className="profile-note"><Check className="h-4 w-4" aria-hidden="true" /><p>This profile supports a clinical conversation. It is not a diagnosis.</p></div>}</section>; }
export function DoctorCard({ doctor, onView, rank }: { doctor: Doctor; onView?: (doctor: Doctor) => void; rank?: number }) { return <article className="doctor-card"><div className="flex items-start justify-between gap-3"><div className={`doctor-avatar doctor-avatar--${doctor.tone}`} aria-hidden="true">{doctor.initials}</div>{rank && <span className="match-rank">{String(rank).padStart(2, "0")}</span>}</div><div className="mt-5"><p className="text-lg font-bold tracking-[-0.035em] text-[var(--ink)]">{doctor.name}</p><div className="mt-2"><SpecialtyBadge specialty={doctor.specialty} /></div></div><div className="doctor-facts"><span><Clock3 className="h-3.5 w-3.5" />{doctor.experience} years</span><span><MapPin className="h-3.5 w-3.5" />{doctor.distance} km</span><span><CalendarDays className="h-3.5 w-3.5" />{doctor.availability}</span></div><p className="mt-5 border-t border-[var(--line)] pt-4 text-sm leading-6 text-[var(--muted-ink)]">{doctor.match}</p><div className="mt-5 flex items-center justify-between gap-3"><span className="font-mono text-xs font-semibold text-[var(--ink)]">₹{doctor.fee} consult</span><button className="text-button" onClick={() => onView?.(doctor)}>View profile <ChevronRight className="h-4 w-4" /></button></div></article>; }
export function PatientCard({ patient, onClick }: { patient: { id: string; complaint: string; date: string; profile: string; status: string; tone: string }; onClick?: () => void }) { return <button className="patient-row" onClick={onClick}><span className={`status-dot status-dot--${patient.tone}`} aria-hidden="true" /><span className="min-w-0 text-left"><span className="font-mono text-[0.64rem] uppercase tracking-[0.14em] text-[var(--muted-ink)]">{patient.id}</span><span className="mt-1 block truncate font-bold tracking-[-0.02em] text-[var(--ink)]">{patient.complaint}</span><span className="mt-1 block truncate text-xs text-[var(--muted-ink)]">{patient.profile}</span></span><span className="hidden text-right text-xs text-[var(--muted-ink)] lg:block">{patient.date}</span><span className="patient-status">{patient.status}</span><ChevronRight className="h-4 w-4 text-[var(--muted-ink)]" /></button>; }
export function MonitoringTimeline({ compact = false }: { compact?: boolean }) { const events = ["Initial concern", "Follow-up", "Screening", "Recommended follow-up"]; return <div className={`monitoring-timeline ${compact ? "monitoring-timeline--compact" : ""}`} aria-label="Screening history timeline">{events.map((event, index) => <div className="monitoring-event" key={event}><span className={`timeline-dot timeline-dot--${index}`} aria-hidden="true" /><p className="font-mono text-[0.58rem] uppercase tracking-[0.13em] text-[var(--muted-ink)]">{index < 3 ? ["Jun 2026", "Jul 2026", "Aug 2026"][index] : "Next step"}</p><p className="mt-1 text-sm font-bold tracking-[-0.02em] text-[var(--ink)]">{event}</p>{!compact && <p className="mt-1 text-xs leading-5 text-[var(--muted-ink)]">{index === 0 ? "Patient-reported change" : index === 1 ? "Continuing concern" : index === 2 ? "Profile structured" : "Clinical conversation"}</p>}</div>)}</div>; }
export function StatCard({ label, value, copy }: { label: string; value: string; copy: string }) { return <article className="stat-card"><p className="font-mono text-[0.6rem] uppercase tracking-[0.14em] text-[var(--muted-ink)]">{label}</p><p className="mt-3 text-4xl font-extrabold tracking-[-0.07em] text-[var(--teal)]">{value}</p><p className="mt-3 text-sm leading-6 text-[var(--muted-ink)]">{copy}</p></article>; }
export function CtaSection() { return <section className="cta-panel"><div className="route-spark route-spark--one" /><div className="route-spark route-spark--two" /><div className="relative z-10 max-w-3xl"><p className="eyebrow text-[var(--turmeric-soft)]">The PxK route begins here</p><h2 className="display-title mt-4 max-w-2xl text-4xl text-white sm:text-5xl">Start with the concern. Find the next step.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/72">Try the patient route or see how structured, patient-reported information flows into clinical follow-up.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn btn-turmeric" href="/patient">Try PxK <ChevronRight className="h-4 w-4" /></Link><Link className="btn btn-ghost-light" href="/how-it-works">Explore how it works</Link></div></div></section>; }
